name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.1.0
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.4.1
      with:
        install: true
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        tags:
          - vlkoti/outofpocket:latest
        platforms:
          - linux/arm64
        push: true
